POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3MTQwMDExNzQsInVzZXJJZCI6MX0.Yguu-Pi33ZwUF8NAsAa8XUIzvKtHzIrNJ4Zn_djPO7o

{
  "name": "Test event antother , maybe dummy new :)!!!!",
  "description": "A test location. Some desc here !!!!",
  "location": "A test location",
  "dateTime": "2025-01-01T15:30:00.000Z"
}
###

POST http://localhost:8080/events
Content-Type: application/json

{
  "name": "Test event2",
  "description": "Test event number 2",
  "location": "Second test location",
  "dateTime": "2025-01-10T15:30:00.000Z"
}