POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3MTM3MTIzMDIsInVzZXJJZCI6MH0.32PJiWG7A353vkKz2CBrt7Ty8ngV_VEj2G5pKtlG9XE

{
  "name": "Test event",
  "description": "A test location",
  "location": "A test location",
  "dateTime": "2025-01-01T15:30:00.000Z"
}
###

POST http://localhost:8080/events
Content-Type: application/json

{
  "name": "Test event2",
  "description": "Test event number 2",
  "location": "Second test location",
  "dateTime": "2025-01-10T15:30:00.000Z"
}