DELETE http://localhost:8080/events/5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzEzOTEwNjY2LCJ1c2VySWQiOjJ9.SVh-WE-6261h6g737jinIzHKesEEDDa7fNvV3obkNRw