PUT http://localhost:8080/events/5
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzEzOTEwMTg5LCJ1c2VySWQiOjJ9.zpR9-lsXpDRMP7rAqBktrZQSewdKNSuZIlP2JeJmD1s

{
    "name": "Updated test event",
    "description": "A test event",
    "location": "Test location (updated)",
    "dateTime": "2025-01-01T15:30:00.000Z"
}